<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QAnyTimeBox
Examples::AddPluginExampleFile('QAnyTimeBox', 'example/anytime.php QAnyTimeBox: Date time picker control');
//// END QAnyTimeBox

//// BEGIN QSlider
Examples::AddPluginExampleFile('QSlider', 'example/qslider.php QSlider: jQuery-based Slider Control');
//// END QSlider

//// BEGIN DialogBoxes
Examples::AddPluginExampleFile('DialogBoxes', 'example/more_dialog_boxes.php * Pre-built Dialog Boxes: Confirmations and Prompts');
//// END DialogBoxes

//// BEGIN QCollapsablePanel
Examples::AddPluginExampleFile('QCollapsablePanel', 'example/collapsablepanel.php QCollapsablePanel: collapsable panel');
//// END QCollapsablePanel

//// BEGIN QCaptchaTextBox
Examples::AddPluginExampleFile('QCaptchaTextBox', 'example/QCaptchaTextBoxExample.php QCaptchaTextBox: Simple example using QCaptcha Textbox');
//// END QCaptchaTextBox

//// BEGIN QGoogleMap
Examples::AddPluginExampleFile('QGoogleMap', 'example/QGoogleMapExample.php Test the Google Map API');
//// END QGoogleMap

//// BEGIN QTabPanel
Examples::AddPluginExampleFile('QTabPanel', 'example/tab_panel.php QTabPanel: jQuery-based Tabs Control');
//// END QTabPanel

//// BEGIN QDateRangePicker
Examples::AddPluginExampleFile('QDateRangePicker', 'example/daterangepicker.php QDateRangePicker: Date range picker control');
//// END QDateRangePicker

//// BEGIN QAutoCompleteTextBox
Examples::AddPluginExampleFile('QAutoCompleteTextBox', 'example/autocomplete.php * Auto-complete Textbox Example');
//// END QAutoCompleteTextBox

//// BEGIN QSelect2ListBox
Examples::AddPluginExampleFile('QSelect2ListBox', 'example/select2listbox.php QSelect2ListBox: QSelect2ListBox: selector control based on select2 JQuery plugin');
//// END QSelect2ListBox

//// BEGIN QFCKEditor
Examples::AddPluginExampleFile('QFCKEditor', 'example/fckeditor.php Rich Text Editing with QFCKEditor');
//// END QFCKEditor

//// BEGIN QCurl
Examples::AddPluginExampleFile('QCurl', 'example/qcurl.php QCurl: Making server-side HTTP requests using a Curl wrapper');
//// END QCurl

?>
