<?php
/**
 * This file is automatically generated and maintained by the
 * QCubed framework. Please do not modify.
 */

//// BEGIN QAnyTimeBox
QApplicationBase::$ClassFile['qanytimebox'] = __PLUGINS__ . '/QAnyTimeBox/includes/QAnyTimeBox.class.php';
QApplicationBase::$ClassFile['qanytimeboxbase'] = __PLUGINS__ . '/QAnyTimeBox/includes/QAnyTimeBoxBase.class.php';
//// END QAnyTimeBox

//// BEGIN QSlider
QApplicationBase::$ClassFile['qslider'] = __PLUGINS__ . '/QSlider/includes/QSlider.class.php';
//// END QSlider

//// BEGIN DialogBoxes
QApplicationBase::$ClassFile['qpromptdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QPromptDialog.class.php';
QApplicationBase::$ClassFile['qtextboxpromptdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QTextBoxPromptDialog.class.php';
QApplicationBase::$ClassFile['qradiobuttonpromptdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QRadioButtonPromptDialog.class.php';
QApplicationBase::$ClassFile['qconfirmationdialog'] = __PLUGINS__ . '/DialogBoxes/includes/QConfirmationDialog.class.php';
//// END DialogBoxes

//// BEGIN QCollapsablePanel
QApplicationBase::$ClassFile['qcollapsablepanel'] = __PLUGINS__ . '/QCollapsablePanel/includes/QCollapsablePanel.class.php';
//// END QCollapsablePanel

//// BEGIN QCaptchaTextBox
QApplicationBase::$ClassFile['qcaptchatextbox'] = __PLUGINS__ . '/QCaptchaTextBox/includes/QCaptchaTextBox.class.php';
QApplicationBase::$ClassFile['qcaptchaimage'] = __PLUGINS__ . '/QCaptchaTextBox/includes/QCaptchaImage.class.php';
QApplicationBase::$ClassFile['qcaptchafilters'] = __PLUGINS__ . '/QCaptchaTextBox/includes/QCaptchaFilters.class.php';
//// END QCaptchaTextBox

//// BEGIN QGoogleMap
QApplicationBase::$ClassFile['qgooglemap'] = __PLUGINS__ . '/QGoogleMap/includes/QGoogleMap.class.php';
//// END QGoogleMap

//// BEGIN QTabPanel
QApplicationBase::$ClassFile['qtabpanel'] = __PLUGINS__ . '/QTabPanel/includes/QTabPanel.class.php';
QApplicationBase::$ClassFile['qtabpanelsection'] = __PLUGINS__ . '/QTabPanel/includes/QTabPanelSection.class.php';
//// END QTabPanel

//// BEGIN QDateRangePicker
QApplicationBase::$ClassFile['qdaterangepicker'] = __PLUGINS__ . '/QDateRangePicker/includes/QDateRangePicker.class.php';
QApplicationBase::$ClassFile['qdaterangepickerbase'] = __PLUGINS__ . '/QDateRangePicker/includes/QDateRangePickerBase.class.php';
//// END QDateRangePicker

//// BEGIN QAutoCompleteTextBox
QApplicationBase::$ClassFile['qautocompletetextboxbase'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QAutoCompleteTextBoxBase.class.php';
QApplicationBase::$ClassFile['qajaxautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QAjaxAutoCompleteTextBox.class.php';
QApplicationBase::$ClassFile['qjavascriptautocompletetextbox'] = __PLUGINS__ . '/QAutoCompleteTextBox/includes/QJavaScriptAutoCompleteTextBox.class.php';
//// END QAutoCompleteTextBox

//// BEGIN QSelect2ListBox
QApplicationBase::$ClassFile['qselect2listbox'] = __PLUGINS__ . '/QSelect2ListBox/includes/QSelect2ListBox.class.php';
QApplicationBase::$ClassFile['qselect2listboxbase'] = __PLUGINS__ . '/QSelect2ListBox/includes/QSelect2ListBoxBase.class.php';
QApplicationBase::$ClassFile['qselect2listboxgen'] = __PLUGINS__ . '/QSelect2ListBox/includes/QSelect2ListBoxGen.class.php';
//// END QSelect2ListBox

//// BEGIN QFCKEditor
QApplicationBase::$ClassFile['qfckeditor'] = __PLUGINS__ . '/QFCKEditor/includes/QFCKEditor.class.php';
//// END QFCKEditor

//// BEGIN QCurl
QApplicationBase::$ClassFile['qcurl'] = __PLUGINS__ . '/QCurl/includes/QCurl.class.php';
//// END QCurl

?>