SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

ALTER TABLE `clms6.0`.`log` ADD COLUMN `data_by` INT(11) NULL DEFAULT NULL  AFTER `log_grp` , CHANGE COLUMN `filename` `filename` VARCHAR(255) NOT NULL  , 
  ADD CONSTRAINT `fk_log_login1`
  FOREIGN KEY (`data_by` )
  REFERENCES `clms6.0`.`login` (`idlogin` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `fk_log_login1` (`data_by` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
